Args = --initialize-at-build-time=com.github.pramodbiligiri.shipsmooth.tasks.jaxb.ObjectFactory \
       --initialize-at-run-time=jakarta.xml.bind.ContextFinder \
       --no-fallback \
       -H:+ReportExceptionStackTraces
